### ISSUE TITLE
Tensorpack update

### ISSUE THREAD

**Issue by rizasif** [YixuanLi/densenet-tensorflow#15]
Hi,

I believe the tensorpack repository has been updated hence your repository needs update too.

I ran the code and the following error appeared:
```
Traceback (most recent call last):
  File "cifar10-densenet.py", line 173, in <module>
    config = get_config()
  File "cifar10-densenet.py", line 142, in get_config
    dataset_train = get_data('train')
  File "cifar10-densenet.py", line 120, in get_data
    imgaug.CenterPaste((40, 40)),
  File "/home/turanshare/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorpack/utils/develop.py", line 151, in __getattr__
    return getattr(module, item)
AttributeError: module 'tensorpack.dataflow.imgaug' has no attribute 'CenterPaste'
```

Apart from `CenterPaste` I think the following lines must be updated:
```
augmentors = [
            imgaug.CenterPaste((40, 40)),
            imgaug.RandomCrop((32, 32)),
            imgaug.Flip(horiz=True),
            #imgaug.Brightness(20),
            #imgaug.Contrast((0.6,1.4)),
            imgaug.MapImage(lambda x: x - pp_mean),
        ]
```

If you have already solved this please let me know. Otherwise I will be happy to generate a pull request with your help.

Thank you.

**Comment by YixuanLi** [comment]
Hi Rizwan,

Please submit the pull request, I will merge on my end once you do so. Thanks!


Sent from my iPhone

On Mar 17, 2018, at 7:54 AM, Rizwan Asif <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I believe the tensorpack repository has been updated hence your repository needs update too.

I ran the code and the following error appeared:

Traceback (most recent call last):
  File "cifar10-densenet.py", line 173, in <module>
    config = get_config()
  File "cifar10-densenet.py", line 142, in get_config
    dataset_train = get_data('train')
  File "cifar10-densenet.py", line 120, in get_data
    imgaug.CenterPaste((40, 40)),
  File "/home/turanshare/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorpack/utils/develop.py", line 151, in __getattr__
    return getattr(module, item)
AttributeError: module 'tensorpack.dataflow.imgaug' has no attribute 'CenterPaste'


Apart from CenterPaste I think the following lines must be updated:

augmentors = [
            imgaug.CenterPaste((40, 40)),
            imgaug.RandomCrop((32, 32)),
            imgaug.Flip(horiz=True),
            #imgaug.Brightness(20),
            #imgaug.Contrast((0.6,1.4)),
            imgaug.MapImage(lambda x: x - pp_mean),
        ]


If you have already solved this please let me know. Otherwise I will be happy to generate a pull request with your help.

Thank you.

**Comment by rizasif** [comment]
Hey, I guess the issue wasn't what I thought it was. Installing OpenCv did the trick and the above issue was solved.

I have, however, submitted a pull request which address this issue as well as another one here: https://github.com/YixuanLi/densenet-tensorflow/pull/16

Thank you.

**Comment by yselivonchyk** [comment]
every time i am getting to this thread, so i'll just leave it here:
`pip install opencv-python`
